name: Pet Pipeline

on:
    push:
        branches:
            - "main"
jobs:
    test:
        name: Unit Tests
        runs-on: ubuntu-22.04
        permissions:
            checks: write
            contents: read

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Setup JDK - 21
                uses: actions/setup-java@v4
                with:
                    distribution: "oracle"
                    java-version: "21"
                    cache: "maven"

            -   name: Run All Tests
                run: mvn test --batch-mode --fail-at-end

            -   name: Publish Test Report
                if: success() || failure()
                uses: scacap/action-surefire-report@v1
